version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: geosearcher
    container_name: geosearcher
    env_file:
      - .env.local
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules